<?php
return array (
  0 => 'bootstrap.php',
  1 => 'nav_logger.php',
  2 => 'database_helpers_1.php',
  3 => 'database_helpers_2.php',
  4 => 'payment_fulfillment.php',
  5 => 'discount_bridge.php',
  6 => 'pricing_fx.php',
  7 => 'bot_api_helpers.php',
  8 => 'business_logic_1.php',
  9 => 'csv_matching_helpers.php',
  10 => 'business_logic_3.php',
  11 => 'business_logic_4.php',
  12 => 'business_logic_5.php',
  13 => 'nm_stock.php',
  14 => 'crypto_helpers.php',
  15 => 'wizard_back.php',
  16 => 'nav_parents.php',
  17 => 'panel_sales_metrics.php',
  18 => 'statistics_helpers.php',
  19 => 'receipt_actions.php',
  20 => 'test_account_policy.php',
);
